version: '3.9'
services:

  app:
    build: ./app
    restart: always
    ports:
      - 5000:5000
    networks:
      - postgredatabase_network
    volumes:
    - ./app:/app
    env_file:
    - .env

networks:
  postgredatabase_network:
    driver: bridge


# volumes:
#   database-data: # named volumes can be managed easier using docker-compose